### ISSUE TITLE
make command errors

### ISSUE THREAD

**Issue by one-eightseven** [CSMathematics/DataTex#10]
Hi, I'm trying to run this application as it looks good for what I need but getting error.

Got ":-1: error: No rule to make target '../../images/Light_Theme/s?ed?as?.svg', needed by 'debug/qrc_Icons.cpp'.  Stop." error

Is there a straightforward way to fix this? (screenshot attached)

Would really appreciate it - thanks for your time. 

<img width="890" alt="image" src="https://github.com/user-attachments/assets/6087dba5-400b-4a44-9f7f-569f2602e7b9">

**Comment by CSMathematics** [comment]
Sorry for that. It was a local file that shouldn't be there.
You can either remove line 3115 in Icons.qrc:
"<file>images/Light_Theme/σχεδίαση.svg</file>" 
or clone the updated version.

P.S. There are still a few bugs I'm working on.
