### ISSUE TITLE
images.qrc missing in the repo

### ISSUE THREAD

**Issue by jojo-Hub** [CSMathematics/DataTex#9]
Hi,

a resource file seems to be missing in the repo:

```shell
[user@host Prog]$ git clone https://github.com/CSMathematics/DataTex.git
[user@host Prog]$ cd DataTex 
[user@host DataTex]$ qmake DataTex.pro
WARNING: Failure to find: images.qrc
/usr/bin/rcc: File does not exist 'images.qrc'
``` 
There is a `qrc_images.cpp` in the root directory. I guess that's the already compiled qrc.

However, if I open the project in QtCreator, I can build the program without any errors (only a couple of warnings).

**Comment by CSMathematics** [comment]
Hi.
Images.qrc has been renamed to Icons,qrc.
Removed line /images.qrc from datatex.pro file.
Hope it works

**Comment by jojo-Hub** [comment]
Thanks, that solved it.

Now I get other issues:

- `qmake`/`make` gives several compiler errors.
- `qmake6`/`make` throws a linker error (`tagslineeditwidget.cpp:(.text+0x9e2): undefined reference to 'TagsPresenter::GetCrossButtonRect(QRect const&) const'` - maybe an issue on my side). Qt Creator with Qt6 in Release mode fails with the same error.
- Qt Creator with Qt6 in Debug mode succeeds to build DataTex. I can also launch it.

That's what my terminal outputs if i start the QT Creator-debug build:

```shell
[user@PC Desktop_Qt6-Debug]$ ./DataTex
QML debugging is enabled. Only use this in a safe environment.
Index =  0
Index =  1
Index =  2
Index =  3
Index =  4
Index =  5
Index =  6
Index =  7
Index =  8
Index =  9
Index =  10
Index =  11
Index =  12
Index =  13
Index =  14
Index =  15
Index =  16
Index =  17
Index =  18
Index =  19
6 6 true
3 3 true
17 17 false
16 16 false
15 15 true
11 11 true
18 18 false
5 5 true
8 8 true
1 1 true
7 7 true
10 10 true
2 2 true
13 13 true
19 19 false
4 4 true
14 14 true
12 12 true
0 0 true
9 9 true
"SELECT df.Id ,ft.Name ,f.Name , replace(group_concat(DISTINCT c.Name),',','|') , replace(group_concat(DISTINCT s.Name),',','|') ,replace(group_concat(DISTINCT et.Name),',','|') ,,df.FileType,ft.Solvable,replace(group_concat(DISTINCT t.Tag_Id),',','|')  FROM Database_Files df JOIN FileTypes ft ON ft.Id = df.FileType JOIN Fields f ON f.Id = df.Field JOIN Chapters_per_File cpf ON cpf.File_Id=df.Id JOIN Chapters c ON c.Id = cpf.Chapter_Id JOIN Sections_per_File spf ON spf.File_Id = df.Id JOIN Sections s ON s.Id = spf.Section_Id  LEFT JOIN Sections_Exercises se ON se.Section_Id = s.Id LEFT JOIN ExerciseTypes_per_File epf ON epf.File_Id = df.Id LEFT JOIN Exercise_Types et ON et.Id = epf.ExerciseType_Id LEFT JOIN Tags_per_File t ON t.File_Id = df.Id GROUP BY df.Id ORDER BY df.rowid;"
QSqlQuery::exec: database not open
QSqlQuery::exec: database not open
QSqlQuery::exec: database not open
QSqlQuery::exec: database not open
```
I'm a bit lost creating and populating a TeX-File database (lot's of crashes or Items can't be added in the wizard) but I'll lave a closer look if I have time. 

BTW: I found 21 occurrences of `/home/spyros/` in the code. Database problems may be related to the `/home/spyros/Έγγραφα/DataBases.json` (?) There is a `databases` directory in the repo, but no `DataBases.json` inside.

**Comment by CSMathematics** [comment]
I use Qt 6.7.2 in Linux if that's helpful.
I don't get the taglinewidget error. But i will take a look. 
Datatex compiles in both Windows and Linux in my machine.
As for the "/home/spyros..." paths , I apologize for the inconvenience. Datatex is still under development and haven't got the time yet to add these files to the resources.
I'll upload an update soon for that.

P.S. Try to comment all taglinewidget occurrences to check if it compiles.

**Comment by jojo-Hub** [comment]
After I removed the `inline` keyword in `custom_widgets/tagspresenter.h:76`, I can also build it from command line:

```shell
qmake6 DataTex.pro
make -j16
./DataTex
```

runs fine :) .

I'll try to dig into the DB-creation-issue and will give some feedback (but this can take some time). I will close this issue as the original issue is solved. Thanks for your work!



PS: I'm on linux as well,
```shell
[user@host ~]$ qmake6 -version
QMake version 3.1
Using Qt version 6.8.0 in /usr/lib
```
BTW: if I use `qmake` (as written in the build notes), this calls Qt5:
```shell
[user@host ~]$ qmake -version
QMake version 3.1
Using Qt version 5.15.15 in /usr/lib
```
and will not succeed to build (maybe this is only important for users with both Qt5 and Qt6).
